### PR TITLE
Adding comment that DSValue.value is of unit ray

### PR DESCRIPTION
**Pull request by lucasvo**

### CODE REVIEW

**Comment by lucasvo** [comment]
Or maybe this is incorrect according to mariano.

**Comment by gbalabasquer** [comment]
Hmm I think the comment should not be there, `ds-value` doesn't define if its value is a `wad`, a `ray` or whatever unit, that depends on each deployment of the contract.

**Comment by lucasvo** [comment]
@gbalabasquer Is this contract used outside of the spotter? If yes then I guess it's true. My reason for adding this was Mariano's comment: 
right now the value of the feeds is a `wad`. The Spotter converts it to a `ray` here https://github.com/makerdao/dss-deploy/blob/5c5a701f18478661eda8971d9f8c58706aa43fd8/src/poke.sol#L51

Maybe this contract is used somewhere else though and it doesn't make sense in that case to add the unit. Is that what you mean?

**Comment by livnev** [comment]
@lucasvo Yeah, this is just a general purpose getter-setter feed, part of the `dappsys` library. The value can be anything, not necessarily an integer of any fixed precision (that's why it's a `bytes32`)

**Comment by gbalabasquer** [comment]
Right. `ds-value` is a package from the dapphub ecosystem that can be used by anyone in whatever context.

**Comment by nanexcool** [comment]
The idea of DSValue is to save whatever you want in it that can fit in 32 bytes.

Our current oracles all use the "wad" ie 18 fixed decimals for representing values but it can really be anything.

edit... just realized everybody responded before me :)

**Pull request closed without merging**
